### ISSUE TITLE
Add Event Task List & Revamp Event Statuses

### ISSUE THREAD

**Issue by benjamin-antupit** [WPI-LNL/lnldb#669]
Create a task list in `Event2019` for Crew Chiefs/VP/T/TD/FL/etc. Event statuses are based on the status of tasks within the event.

Layouts (similar filters and sorting available in all):
- My tasks
- Tasks assigned to a specific user (for officers)
- Event tasks (available inside event details, shows all tasks for the event)
- Ideally, this would integrate with the LNL Slackbot to show a user's task list & provide task reminders inside Slack

Current thoughts on task flow:
- (someday) events with LNL requested in 25Live create task for VP
    - VP can associate 25Live booking with LNLDB event within task
- [ ] On event creation, create a task list with default tasks. Default tasks can be modified by anyone with the `Officer` role. 
    - [ ] Default tasks are available for specific services, spaces, or for all events
    - [ ] Add default tasks when locations or services are changed (and mark invalid when locations/services change)
- VP tasks are assigned to VP and show up in their `todo` section
    - Can be reassigned by VP or anyone with the `Officer` role as needed
    - Certain tasks may allow a file to be uploaded to complete them (e.g. task for asking the client to approve the quote could allow a PDF or screenshot to be uploaded with it)
- When crew chiefs are assigned, all CCs are assigned the CC tasks. Any CC can complete any of the tasks or add another user as an additional person assigned who can complete the task.
    - Example task for all events: Will a lift be needed for setup? If so, which days/times and which lift? --> TD & FL get assigned an acknowledgment task that a lift is needed
    - Example task based on status: when CCs are assigned, add President task to request temp IDs for CCs without office access
    - Example task for events with advanced lighting: Upload a plot & patch prior to setup start
    - After the event: confirm crew hours and complete CC reports --> VP gets assigned a task to complete an event review

Current thoughts on status flow:
- New events start as `Requested (Awaiting Approval)`. Only visible to Officers.
    - If an event is added before it is requested (since we anticipate a request), the status is `Anticipated (Awaiting Request)`
- Upon completion of VP approval tasks and once VP approves the event, status is `Approved (Awaiting CCs)`
    - During this stage, VP can choose when the event is visible to members. Once approved, the event will automatically become visible for the rest of the process unless marked `Sensitive`.
- Once CC(s) have been assigned, the status is `Upcoming (Approved)`
- Once the first setup begins, the status is `Setup In Progress`
- Once the event begins, the status is `Event in Progress`
- Once the event ends, the status is `Complete (Awaiting Review)`
- Once reviewed the status is `Complete (Awaiting billing)`, then `Complete (Awaiting payment)`, then `Complete (Paid)`
Other statuses:
- The event could be `Closed (Cancelled)` if the event is denied, canceled or otherwise closed before completion
 
If this system works well, a similar task-based system could be added for training and PIT requests.
