### ISSUE TITLE
Add Rental Tracking

### ISSUE THREAD

**Issue by benjamin-antupit** [WPI-LNL/lnldb#755]
- [ ] model for rental vendor with contact info. 
- [ ] model for rental item with quote. 
- [ ] model for rental quote (a quote given to us) with options to add rental items with qty and price
- [ ] Allow rental quote to be added to event billing (with option to hide rental vendor name and break down by category or item, i.e. `Lighting Equipment: $100` or `1x Mac Aura: $100`)
